project:
  type: website
  output-dir: docs
  resources: files

website:
  title: "Stefan Britz"
  favicon: logo.png
  site-url: https://github.com/SSBritz/Personal_site
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Education
        href: education.qmd
      - text: Supervision
        href: supervision.qmd
      - text: Talks
        href: talks.qmd
      - text: Publications
        href: publications.qmd
      # - text: Blog posts
      #   href: blog.qmd
    right:
      - icon: github
        href: https://github.com/      

body-footer: | 
  Copyright:  Stefan Streicher Britz, 2025

date-format: "December 2025" #Try Sys.date() maybe?

format:
  html:
    theme: 
      - pulse
      - custom.scss
    toc: true

